[project]
name = "core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google>=3.0.0",
    "nats-py>=2",
    "numpy>=2.2.6",
    "protobuf>=6.31.1",
    "sounddevice>=0.5.2",
]
